# Generated by Django 5.2.11 on 2026-02-17 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField(help_text="Price in your currency")),
                ("rating", models.FloatField(help_text="Rating from 0 to 5")),
                (
                    "performance",
                    models.FloatField(help_text="Performance score from 0 to 100"),
                ),
                (
                    "battery",
                    models.FloatField(
                        help_text="Battery score from 0 to 100 (or battery hours)"
                    ),
                ),
                (
                    "value_score",
                    models.FloatField(
                        blank=True, help_text="Optional value score", null=True
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL to item image", max_length=500
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
